In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from sklearn import datasets, linear_model, metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [2]:
df=pd.read_csv("Swiggy Final Data.csv")

In [3]:
df

Restaurant_Name        Cuisine      Location  Unnamed: 3   Rating   
0             Malabar Bay       Desserts   koramangala         NaN  10000.0  \
1             Malabar Bay        Biryani   koramangala         NaN  10000.0   
2             Malabar Bay       Desserts   koramangala         NaN  10000.0   
3             Malabar Bay   South Indian   koramangala         NaN  10000.0   
4             Malabar Bay   South Indian   koramangala         NaN  10000.0   
...                   ...            ...           ...         ...      ...   
8198        Sweet Chariot       Desserts  malleshwaram         NaN   1000.0   
8199      Rohan's Kitchen       American   indiranagar         NaN     50.0   
8200          Malabar Bay        Biryani   koramangala         NaN  10000.0   
8201  Fresh Pressery Cafe       Healt...   koramangala         NaN  10000.0   
8202      Thali's Station         Thalis        layout         NaN    100.0   

                                       Dish_Name  Dish_Price  
0                                  veg julfreizi      180.00  
1                             paneer tawa masala      220.00  
2                           paneer butter masala      220.00  
3                                mur mura bhindi      160.00  
4                                    malai kofta      230.00  
...                                          ...         ...  
8198                Fresh Cream Mango Glaze Cake       61.90  
8199   Creamy Mushroom  Scrambled Egg With Toast      199.00  
8200                     Chilli Cheese Egg Appam       75.00  
8201                                     Chicken      185.41  
8202                   Aloo Jeera Thali (in 5cp)      189.00  

[8203 rows x 7 columns]

In [4]:
# Drop unwanted Column
df.drop("Unnamed: 3",axis=1,inplace=True)

In [5]:
# Drop null values
df.dropna(inplace=True)

In [6]:
df["Location"].unique
df[""]

<bound method Series.unique of 0        koramangala
1        koramangala
2        koramangala
3        koramangala
4        koramangala
            ...     
8198    malleshwaram
8199     indiranagar
8200     koramangala
8201     koramangala
8202          layout
Name: Location, Length: 8051, dtype: object>

In [7]:
df.isnull().sum()

Restaurant_Name    0
Cuisine            0
Location           0
Rating             0
Dish_Name          0
Dish_Price         0
dtype: int64

In [8]:
# Apply label encodeing in each categorycal column
from sklearn.preprocessing import LabelEncoder
le_Restaurant_Name = LabelEncoder()
df['Restaurant_Name'] = le_Restaurant_Name.fit_transform(df['Restaurant_Name'])
df["Restaurant_Name"].unique()

array([216,   5, 177,  86, 408, 178, 285,  44, 263, 371, 264, 228, 176,
       121, 337, 179,  47, 280, 272, 148, 398,  69, 128,  65, 421, 170,
       113, 273, 451,  67,  11, 175,  68,  64, 167, 412,  75, 317, 158,
       289,  32, 333, 242, 209, 157, 321,  54, 181, 391,  92, 329, 281,
       304, 120, 444,  62, 107, 387, 383,  12, 189,   1, 174, 191, 365,
       125, 325, 438,  91,  74,  94, 369,  59, 103, 423, 118, 265,  89,
        48, 162,  84, 257,  95, 326, 406, 341, 247, 348,  60, 260, 287,
       277, 417, 448, 196, 163, 439, 454, 122, 459, 457, 241, 366, 146,
       425, 248, 274, 299, 292, 460, 455, 401, 452,  71, 159, 254, 262,
        49,  78, 119, 208, 276, 199, 306, 355, 418, 226, 433, 311, 249,
       135, 335, 319, 166, 381, 361,  17, 288, 294, 397, 131, 232, 284,
       330,  37, 282, 338, 404, 315, 290, 410, 437, 204, 279, 240,   3,
        87, 183, 238, 340,  22, 434, 133, 346,  58, 354, 220, 385, 155,
       328, 295, 353, 307, 357, 251, 153, 243, 405, 430,  38, 33

In [9]:
# Apply label encodeing in each categorycal column
le_Cuisine = LabelEncoder()
df['Cuisine'] = le_Cuisine.fit_transform(df['Cuisine'])
df["Cuisine"].unique()

array([ 19,   9,  57,  15,  75,  73,   7,  21,  95,  17,  37,  70,  29,
        84,   6,  86,  23,  33,  82, 102,  72,  87,  56,  61,  79,  91,
        46,  12,  54,  55,  85,  62,  89,  26,  81,   5,  99, 101,  28,
        48,   0,  13,  96,  88,  24,  31,  71,  34,   3,  14, 105,  97,
        92,  65,  52,  11, 103,  40,  59,  74,  80,  45,  64,  47,  67,
        63, 104,  35,  36,  43,  16,   1,  32,  78,  60,  30,  39,  44,
        50,  98,  27,  77,  41,  38,  10,  93,  25,  49,  58,  68,   8,
       100,  76,  20,  18,  69,  83,  53,  22,  66,   4,  94,  42,  51,
        90,   2])

In [10]:
# Apply label encodeing in each categorycal column
le_Location = LabelEncoder()
df['Location'] = le_Location.fit_transform(df['Location'])
df["Location"].unique()

array([18, 30, 25, 13, 10, 29, 37,  8, 35, 16,  9, 14, 20, 24, 27, 15,  1,
        2, 38, 28, 32,  7, 17, 12,  4, 19, 11, 33, 23, 36, 26,  0,  6, 22,
       31, 21, 39,  5,  3, 34])

In [11]:
# Apply label encodeing in each categorycal column
le_Dish_Name = LabelEncoder()
df['Dish_Name'] = le_Dish_Name.fit_transform(df['Dish_Name'])
df["Dish_Name"].unique()

array([6427, 6426, 6425, ...,    2,    1,    0])

In [12]:
X = df.drop(["Dish_Price",'Location'], axis=1)
y = df[["Dish_Price","Location"]]

In [13]:
from sklearn.linear_model import LinearRegression
linear_reg = LinearRegression()
linear_reg.fit(X, y.values)

LinearRegression()

In [14]:
y_pred = linear_reg.predict(X)

In [15]:
from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np
error = np.sqrt(mean_squared_error(y, y_pred))

In [16]:
error

114.38761164894798

In [17]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'fit_intercept': [True, False],
    
}

regressor = LinearRegression()
gs = GridSearchCV(regressor, param_grid, cv=5, scoring='neg_mean_squared_error')
gs.fit(X, y)

GridSearchCV(cv=5, estimator=LinearRegression(),
             param_grid={'fit_intercept': [True, False]},
             scoring='neg_mean_squared_error')

In [18]:
regressor = gs.best_estimator_

regressor.fit(X, y.values)
y_pred = regressor.predict(X)
error = np.sqrt(mean_squared_error(y, y_pred))
print("${:,.02f}".format(error))

$114.39


In [19]:
X = np.array([[  'Malabar Bay',"Desserts",'koramangala',"veg julfreizi" ]])
X

array([['Malabar Bay', 'Desserts', 'koramangala', 'veg julfreizi']],
      dtype='<U13')

In [20]:
X[:, 1] = le_Cuisine.transform(X[:, 1])
X[:, 2] = le_Location.transform(X[:, 2])
X[:, 3] = le_Dish_Name.transform(X[:, 3])
X[:, 0] = le_Restaurant_Name.transform(X[:, 0])

X = X.astype(float)
X

array([[ 216.,   82.,   18., 6427.]])

In [21]:
y_pred = regressor.predict(X)
y_pred

C:\Users\khana\.conda\envs\ml\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[173.02543215,  17.84042262]])

In [22]:
import pickle

In [23]:
# save machine learning model with pickel libery
data = {"model": regressor, "le_Cuisine": le_Cuisine, "le_Location": le_Location,"le_Dish_Name":le_Dish_Name}
with open('saveded_steps.pkl', 'wb') as file:
    pickle.dump(data, file)

In [24]:
with open('saveded_steps.pkl', 'rb') as file:
    data = pickle.load(file)

regressor_loaded = data["model"]
le_Cuisine = data["le_Cuisine"]
le_Location = data["le_Location"]
le_Dish_Name = data["le_Dish_Name"]

In [25]:
y_pred = regressor_loaded.predict(X)
y_pred

C:\Users\khana\.conda\envs\ml\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[173.02543215,  17.84042262]])